-- Create table for Car Makes
create table if not exists car_makes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create table for Car Models
create table if not exists car_models (
  id bigint generated by default as identity primary key,
  make_id bigint references car_makes(id) on delete cascade not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(make_id, name)
);

-- Enable Row Level Security (RLS)
alter table car_makes enable row level security;
alter table car_models enable row level security;

-- Create policies to allow public read access
create policy "Allow public read access" on car_makes for select using (true);
create policy "Allow public read access" on car_models for select using (true);

-- Create policies to allow service_role only for modifications (synced via Edge Function)
-- No public insert/update/delete
